### ISSUE TITLE
Access violation in VS2015

### ISSUE THREAD

**Issue by Zephyrrus** [Bill-Gray/PDCurses#29] opened 2017-03-22 19:58 UTC
I tried using the win32 and win32a in one of my projects, but as soon as I try to do anything with curses I get 
```
Exception thrown at 0x0F7E42E3 (pdcurses.dll) in L5-L6.exe: 0xC0000005: Access violation reading location 0x0060A535.
```

Example of code that causes that for me
```cpp
#include <curses.h>

int main()
{
	initscr();			/* Start curses mode 		  */
	printw("Hello World !!!");	/* Print Hello World		  */
	refresh();			/* Print it on to the real screen */
	getch();			/* Wait for user input !!!THIS IS WHERE IT BREAKS */ 
	endwin();			/* End curses mode		  */

	return 0;
}
```

I can compile the demos just fine with nmake, but as soon as I try to use visual studio (pretty sure it uses the same compiler) I get the Access violation error. Trying to compile tui.c gives the same error on the line 
```cpp
wtitl = subwin(stdscr, th, bw, 0, 0);
```

**Comment by GitMensch** [comment] 2017-03-22 20:09
I assume you use the most current one from master?
Can you please compile both PDCurses and your test program with debug information, add a breakpoint at  `getch` and jump into the function to see where it breaks?

**Comment by Zephyrrus** [comment] 2017-03-22 20:27
That took me some time because `-pdb:none` will create a very messed up file (it merges all symbols into a file called none instead of not creating pdbs).

It looks like the function `wgetch`  causes the exception to be thrown, here's a screenshot of the exact line where it happens http://i.imgur.com/NkoaBxx.png

**Comment by bowerscd** [comment] 2017-04-02 17:57
I too had this issue - I resolved it by defining PDC_DLL_BUILD at the top of curses.h

**Comment by Bill-Gray** [comment] 2017-04-02 21:03
@bowerscd - good thought;  the error message mentions pdcurses.dll,  and the source code doesn't #define PDC_DLL_BUILD.  So I think you got it.

I've had issues with defining PDC_BUILD_DLL and then linking to a static library,  and with _not_ defining it and linking to a DLL.  Also with libraries built with WIDE=Y or UTF8=Y that didn't match the way I built the program.  Also,  we now have the ability to mix and match CHTYPE16=Y,  CHTYPE32=Y, and the default 64-bit chtypes.

**Comment by GitMensch** [comment] 2017-04-06 06:58
@Bill-Gray It seems that PDCurses doesn't register a signal handler (would be done in `initscr()`). This may be a good idea (code from GnuCOBOL's libcob/common.c could be borrowed, if needed), at least for the new win32a interfaace.
If a signal handler is in it could check for compile/library differences including PDC_BUILD and print these along a nice error message.

**Comment by Bill-Gray** [comment] 2017-05-01 23:34
@GitMensch - I'm going through and closing some old and now fixed issues.  This is one of them,  except for your comment about signal handling.

The problem is that when initscr() is called,  and for quite a while after that,  we don't have a way (at runtime) to check such issues.  At some point,  somebody will make a call with a chtype of incorrect size (for example),  and the library will either read/write some bits it shouldn't (if it was built with,  say,  64-bit chtypes and the app with 32-bit chtypes),  or fail to set bits it should (in the opposite case).  In the first case,  we probably segfault.  In the second case,  we display garbage.  In neither case do we really have a good diagnostic to provide;  it requires some human interpretation.

I could imagine something where,  say,  'initscr' is #defined based on flags,  such that if it's a DLL build with UTF8 and 64 bits,  it expands to 'initscr_dll_utf8_64'.  If you compile the library that way,  and then compile your app with 32-bit chtypes,  it expands to 'initscr_dll_utf8_32',  and you get an unresolved external at compile time.  (Or,  if somebody slips in the wrong DLL later,  you get a message that the DLL doesn't contain the latter function.)

**Comment by GitMensch** [comment] 2017-08-22 21:17
I suggest to close this issue now. We may create a new one for the last mentioned part, now that we have version information in both during building actual pdcurses library (with the attributes stored in the header) and when running `initscr()` checking that at least the chtypes are identical (otherwise we'll abort quite soon anyway) and do a "clean" abort with providing the error reason.
The need for a clean abort may be true for wide/utf-8 or other stuff, too (you'd know this better), as I've understood this only the curses platform may be changed (win32<-->win32a/sdl2/...)

**Closed** 2018-12-24 23:51 UTC
