### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by flypie** [Bill-Gray/PDCurses#32] opened 2017-04-26 01:00 UTC

**Comment by Bill-Gray** [comment] 2017-04-26 01:29
Errrm... possibly telling you what you've just figured out,  but I'll reopen just long enough to mention the following:

This is a near-duplicate of issue #14,  on which we've been working for a bit now:

https://github.com/Bill-Gray/PDCurses/issues/14

Bottom line:  I think if you get the two files described there,

http://www.projectpluto.com/PDCurses/mingnew.mak
http://www.projectpluto.com/PDCurses/pdcscrn.c

(the first is a new file,  the latter replaces an existing file),  you should be all set.  We've run into assorted issues in which __argc,  __argv,  and wide versions of these,  either were or were not available on Cygwin or MinGW or when cross-compiling.  I think they're all sorted.  I haven't closed #14 because I've not gotten much feedback on it,  and am not really sure it's all sorted (can only say "works fine for me",  on many configurations.)

**Closed by Bill-Gray** 2017-04-26 01:29 UTC

**Comment by flypie** [comment] 2017-04-29 01:16
I switched the Visual C build, that works fine. Thanks anyway.
