### ISSUE TITLE
win32a fails to compile pdcscrn.c on Cygwin (GCC 5.4.0)

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCurses#14] opened 2016-09-11 18:20 UTC
```
../win32a/pdcscrn.c: In function 'get_app_name':
../win32a/pdcscrn.c:953:39: error: '__argc' undeclared (first use in this function)
     int argc = (PDC_argc ? PDC_argc : __argc);
                                       ^
../win32a/pdcscrn.c:953:39: note: each undeclared identifier is reported only once for each function it appears in
../win32a/pdcscrn.c:954:42: error: '__argv' undeclared (first use in this function)
     char **argv = (PDC_argc ? PDC_argv : __argv);
                                          ^
../win32a/pdcscrn.c:1000:9: warning: implicit declaration of function '_splitpath' [-Wimplicit-function-declaration]
         _splitpath( argv[0], NULL, NULL, buff, NULL);
         ^
../win32a/pdcscrn.c:1014:9: warning: implicit declaration of function '_strlwr' [-Wimplicit-function-declaration]
         _strlwr( buff + 1);
         ^
../win32a/pdcscrn.c:1024:70: error: '__wargv' undeclared (first use in this function)
     debug_printf( "__argv: %p __wargv: %p Name out: '%s'\n", __argv, __wargv, buff);
                                                                      ^
../win32a/pdcscrn.c:1026:5: warning: implicit declaration of function '_tcslwr' [-Wimplicit-function-declaration]
     _tcslwr( buff + 1);
     ^
../win32a/pdcscrn.c: In function 'get_app_icon':
../win32a/pdcscrn.c:1037:19: error: '_MAX_PATH' undeclared (first use in this function)
     char filename[_MAX_PATH];
                   ^
../win32a/pdcscrn.c:1037:10: warning: unused variable 'filename' [-Wunused-variable]
     char filename[_MAX_PATH];
          ^
../win32a/pdcscrn.c: In function 'set_default_sizes_from_registry':
../win32a/pdcscrn.c:1067:24: error: '_MAX_PATH' undeclared (first use in this function)
         TCHAR key_name[_MAX_PATH];
                        ^
../win32a/pdcscrn.c:1071:13: warning: implicit declaration of function '_sntprintf' [-Wimplicit-function-declaration]
             _sntprintf( buff, sizeof( buff),
             ^
../win32a/pdcscrn.c:1077:28: warning: implicit declaration of function '_tcslen' [-Wimplicit-function-declaration]
         _sntprintf( buff + _tcslen( buff), sizeof( buff) - _tcslen( buff),
                            ^
../win32a/pdcscrn.c:1081:9: warning: implicit declaration of function '_tcscat' [-Wimplicit-function-declaration]
         _tcscat( buff, PDC_font_name);
         ^
../win32a/pdcscrn.c:1067:15: warning: unused variable 'key_name' [-Wunused-variable]
         TCHAR key_name[_MAX_PATH];
               ^
../win32a/pdcscrn.c: In function 'get_default_sizes_from_registry':
../win32a/pdcscrn.c:1283:24: error: '_MAX_PATH' undeclared (first use in this function)
         TCHAR key_name[_MAX_PATH];
                        ^
../win32a/pdcscrn.c:1293:13: warning: implicit declaration of function '_stscan ' [-Wimplicit-function-declaration]
             _stscanf( data, _T( "%dx%d,%d,%d,%d,%d;%d,%d,%d,%d:%n"),
             ^
../win32a/pdcscrn.c:1300:16: warning: implicit declaration of function '_tcscpy' [-Wimplicit-function-declaration]
                _tcscpy( PDC_font_name, data + bytes_read);
                ^
../win32a/pdcscrn.c:1283:15: warning: unused variable 'key_name' [-Wunused-variable]
         TCHAR key_name[_MAX_PATH];
               ^
../win32a/pdcscrn.c: In function 'set_up_window':
../win32a/pdcscrn.c:2184:23: error: '_MAX_PATH' undeclared (first use in this function)
     TCHAR WindowTitle[_MAX_PATH];
                       ^
../win32a/pdcscrn.c:2184:11: warning: unused variable 'WindowTitle' [-Wunused-variable]
     TCHAR WindowTitle[_MAX_PATH];
           ^
make: *** [gccwin32.mak:104: pdcscrn.o] Error 1
```

The same error occurs when using mingwin32.mak

win32 builds fine (with gccwin32.mak).

**Comment by Unknown78** [comment] 2017-01-15 11:34
# **I have the same issue!**
 This need to be fixed!

**Comment by Bill-Gray** [comment] 2017-01-16 02:05
OK,  a warning here:  I don't have a machine set up with Cygwin.
I was sort of hoping that somebody who did would take a stab at
this.  Since that hasn't happened,  and since I _think_ it'll be
reasonably straightforward,  and since I'm assuming you've just
volunteered to test it (thank you!),  I've started in on the job.
Please try the following :

http://www.projectpluto.com/PDCurses/mingnew.mak
http://www.projectpluto.com/PDCurses/pdcscrn.c

The former attempts to use some 'uname' trickery to determine if
one is on Cygwin,  a "real" Windows system,  or cross-compiling
from Linux or *BSD.  The latter ought to diminish the number of
errors you see when compiling on Cygwin.

I _think_ the problem is that Cygwin is using an older flavor of
MinGW that lacks various "improvements" that are found in the MinGW
that I'm running in Linux and on a Windows box.  The above version
of pdcscrn.c tries to fix at least two of these issues.

First,  if you look at the get_app_name() function,  you'll see that
if GOT_ARGV_ARGC is not defined,  we don't try to set the app name
using __argc and __argv.  We use PDC_arg* if they've been set (i.e.,
Xinitscr() was used instead of initscr()),  and if that fails,
we fall back on GetCommandLine().

Determining when GOT_ARGV_ARGC should be defined (i.e.,  situations
where __argv and __argc are actually declared) may be a little hard.
I assume there's some version of MinGW where they were introduced,
and that Cygwin uses an older version.  If,  for example,  versions
4.06 and later have __argv and __argc but earlier versions do not,
we'll have to do something such as

#if ((__GNUC__ * 100) + __GNUC_MINOR__) >= 406
    #define GOT_ARGV_ARGC
#endif

(It would be nice if we could instead do something like

#if !declared( __argv)
    const char **__argv = NULL;
#endif

Sadly,  I don't think a way exist of doing that.)  For the nonce,  to
test things out,  I'm just leaving GOT_ARGV_ARGC undefined.

Also,  a bit of on-line searching suggests to me that there is no good
reason to use _MAX_PATH instead of MAX_PATH.  Dropping that underscore
should eliminate some more errors.

This does leave us with _splitpath,  _strlwr,  _sntprintf,  _tcslen,
_tcscat,  _stscanf,  and _tcscpy.  But if you (and/or Simon) tell me
what you see with the two files cited above,  we can progress from there.

-- Bill

**Comment by citizen4371** [comment] 2017-03-14 21:27
Hi, Bill, I've tried to compile with two aforementioned files, and as you've predicted the problem now is with _splitpath,  _strlwr, etc.

**Comment by Bill-Gray** [comment] 2017-03-15 01:43
Thanks for replying on this,  and confirming that the fix worked (as far as I went,  obviously not enough yet).  As you probably saw,  I posted this fix in January,  and got no feedback until you replied.  So I had no idea if I'd actually fixed anything or not.

I've just posted a new version of that same file,

http://www.projectpluto.com/pdcscrn.c

It has the same fixes,  some updates made since January,  and an attempt to fix the "underscore" issues.  If you look at lines 1001-1008,  I simply #defined the underscore versions to map the non-underscore versions.  Please let me know if that works.  (If we're lucky,  it will fix all the errors.  If not,  I'm hoping Cygwin knows about at least _most_ of those functions... they are not all that strange and exotic!)

If it does work,  I will have to make sure that those lines are only compiled when using Cygwin;  they cause trouble under MinGW,  at least,  and probably elsewhere.  But that part ought to be easy... the key thing is that I need to know if those eight lines cause the code to compile and run with Cygwin.

**Comment by citizen4371** [comment] 2017-03-15 08:16
Hey, thanks for the quick response, got bad news for you though, cygwin knows none of non-undersored function, he's basically Jon Snow

**Comment by GitMensch** [comment] 2017-03-15 10:33
I've somehow missed these updates (but see the current one as I've watched the project). I'll investigate this with a Cygwin environment soon - what files have the minimal changes that I should try when using the latest version from git?

**Comment by Bill-Gray** [comment] 2017-03-15 16:45
Minimum changes you'd need would be to have "current" PDCurses code,  then get these two files into PDCurses/win32a :

 http://www.projectpluto.com/PDCurses/mingnew.mak
 http://www.projectpluto.com/PDCurses/pdcscrn.c

    ...with the latter replacing your existing pdcscrn.c.  Then make using mingnew.mak.  Then... sounds as if we have to work around the fact that there's no splitpath or wsplitpath,  with or without an underscore,  and similarly for the other six functions at lines 1001-1008.

   For wsplitpath and splitpath,  we have one thing in our favor:  all we're trying to get is the program name,  minus the drive,  path,  and extension (i.e.,  from c:\randompath\morepath\testcurs.exe,  just get testcurs).  For the nonce,  you can replace a line such as

_splitpath( argv[0], NULL, NULL, tbuff, NULL);

   with

strcpy( tbuff, "random_name");

   For the remaining six functions,  maybe something like the following will work :

#ifdef CYGWIN
#ifdef UNICODE
   #define _sntprintf wsnprintf
   #define _tcslen wstrlen
   #define _tcslwr wstrlwr
  (similarly for three more functions)
#else    /* start non-wide char versions */
   #define _sntprintf snprintf
   #define _tcslen strlen
   #define _tcslwr strlwr
  (similarly for three more functions)
#endif   /* #ifdef UNICODE */
#endif   /* #ifdef CYGWIN */

**Comment by Bill-Gray** [comment] 2017-03-15 17:17
Correction:  just updated the 'pdcscrn.c' at the above URL so that it should work,  even under Cygwin.  Trick was to realize that I could have those #defines work on other compilers;  it didn't have to be a Cygwin-specific solution (look around line 1000 and you'll see what I mean).  Still leaves the _splitpath and _wsplitpath,  though.

**Comment by Bill-Gray** [comment] 2017-03-15 21:03
Hmm... something kinda odd there... I just tried to open 'pdcscrn.c' from my browser and also got the old version.  I cleared the cache,  tried again,  and all was well.

In place of the redefinitions I had starting at line 1000,  you should see the following,  with the underscored functions now prefaced by 'my_'.  (With those being used for all compilers;  I didn't see why it should be Cygwin-specific.)

#ifdef CYGWIN
   #define _splitpath  splitpath
   #define _wsplitpath splitpath
#endif

#ifdef UNICODE
   #define my_stprintf wsprintf
   #define my_tcslen   wcslen
   #define my_tcslwr   wcslwr
   #define my_tcscat   wcscat
   #define my_tcscpy   wcscpy
   #define my_stscanf  swscanf
#else
   #define my_stprintf sprintf
   #define my_tcslen   strlen
   #define my_tcslwr   strlwr
   #define my_tcscat   strcat
   #define my_tcscpy   strcpy
   #define my_stscanf  sscanf
#endif

**Comment by citizen4371** [comment] 2017-03-17 08:33
I found out that the correct cygwin check is #ifdef __CYGWIN__

**Comment by citizen4371** [comment] 2017-03-17 08:44
Also, cygwin doesn't like _strlwr on line 1091

**Comment by Bill-Gray** [comment] 2017-03-17 12:48
"... cygwin doesn't like _strlwr on line 1091"

Hang on!  Is that the only remaining error message?  We've gotten around the splitpath and wsplitpath problems,  and the other string-handling functions are OK?

If so,  we're closer to resolving this than I thought.  Change that '_strlwr' to 'strlwr' (no underscore) and it should work.  (Or at least compile.  At least in non-Unicode mode.)  If it still fails,  we'll have to supply our own strlwr function,  but that's only a couple of lines... and I'd be rather surprised if it failed;  we'd be getting a message at line 1102 if such were the case.

**Comment by citizen4371** [comment] 2017-03-22 15:45
Finally had a chance to test again, so answering your question: the problem with splitpath still remains, I just didn't mention it, cause we've been already expecting it.

**Comment by Bill-Gray** [comment] 2017-03-22 17:22
OK,  I looked into splitpath and wsplitpath;  they turn out not to be rocket surgery.  I've (again) updated http://www.projectpluto.com/pdcscrn.c ,  this time with implementations of each,  only compiled if __CYGWIN__ is #defined.  If this works,  in both wide-character and non-wide versions,  with the correct program name shown on the application title bar,  then I think we're good to go.

**Comment by citizen4371** [comment] 2017-03-30 12:29
Congrats, it does compile (keep in mind, though, that _strlwr should be changed to strlwr). The problem I have now appears when I try to compile my code with pdcurses linked (a lot of 'relocation truncated to fit' errors)

**Comment by Bill-Gray** [comment] 2017-05-01 22:22
I've just committed the revisions for 'pdcscrn.c' and 'mingwin32.mak':

https://github.com/Bill-Gray/PDCurses/commit/1552db2cf6eb3698cf05c6cbdf8704f3beef44e4
https://github.com/Bill-Gray/PDCurses/commit/5edff592f712110b36adec547c6817dacf2ec0a8

I think with these changes,  everything does work on Cygwin,  and does so in a manner that doesn't break other platforms.  So I'm closing this.

**Closed by Bill-Gray** 2017-05-01 22:22 UTC
